app/urls.py
from django.urls import path
from .views import cliente_views, pet_views, consulta_views

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente, name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('listar_cliente/<int:id>', cliente_views.listar_cliente, name='listar_cliente'),
    path('editar_cliente/<int:id>', cliente_views.editar_cliente, name='editar_cliente'),
    path('remover_cliente/<int:id>', cliente_views.remover_cliente, name='remover_cliente'),
    path('cadastrar_pet/<int:id>', pet_views.cadastrar_pet, name='cadastrar_pet'),
    path('listar_pet/<int:id>', pet_views.listar_pet_id, name='listar_pet_id'),
    path('cadastrar_consulta/<int:id>', consulta_views.inserir_consulta, name='cadastrar_consulta'),
    path('lista_consulta/<int:id>', consulta_views.listar_consulta_id, name='listar_consulta_id'),
]

gerenciamento_pet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls'))
]

app/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES

# Classe endereço cliente
from spacy import blank


class EnderecoCliente(models.Model):


    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(max_length=2, choices=STATE_CHOICES, null=False, blank=False)

# Classe cliente
class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)

# Classe pet
class Pet(models.Model):
    CATEGORIA_PET_CHOICES = (
        ('Ca', 'Cachorro'),
        ('Ga', 'Gato'),
        ('Co', 'Coelho'),
    )

    COR_PET_CHOICES = (
        ('Pr', 'Preto'),
        ('Br', 'Branco'),
        ('Ci', 'Cinza'),
        ('Ma', 'Marrom'),
    )

    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    categoria = models.CharField(max_length=2, choices=CATEGORIA_PET_CHOICES, null=False, blank=False)
    cor = models.CharField(max_length=2, choices=COR_PET_CHOICES, null=False, blank=False)
    dono = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=False, blank=False)

class ConsultaPet(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    motivo_consulta = models.CharField(max_length=200, null=False, blank=False)
    peso_atual = models.FloatField(null=False, blank=False)
    medicamento_atual = models.TextField(null=False, blank=True)
    medicamentos_prescritos = models.TextField(null=False, blank=True)
    exames_prescritos = models.TextField(null=False, blank=True)

app/forms/pet_forms.py
from django import forms
from ..models import Pet

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['nome', 'nascimento', 'categoria', 'cor']
        exclude = ['dono', ]

app/views/pet_views.py
from django.shortcuts import render, redirect
from ..forms import pet_forms
from ..entidades import pet
from ..services import pet_service, cliente_service, consulta_service


def cadastrar_pet(request, id):
    if request.method == "POST":
        form_pet = pet_forms.PetForm(request.POST)
        dono = cliente_service.listar_cliente_id(id)
        if form_pet.is_valid():
            nome = form_pet.cleaned_data["nome"]
            nascimento = form_pet.cleaned_data["nascimento"]
            categoria = form_pet.cleaned_data["categoria"]
            cor = form_pet.cleaned_data["cor"]
            pet_novo = pet.Pet(dono=dono, nome=nome, nascimento=nascimento, categoria=categoria,
                                        cor=cor)
            pet_service.cadastrar_pet(pet_novo)
            return redirect('listar_clientes')
    else:
        form_pet = pet_forms.PetForm()
    return render(request, 'pets/form_pet.html', {'form_pet': form_pet})

def listar_pet_id(request, id):
    pet = pet_service.listar_pet_id(id)
    consultas = consulta_service.listar_consultas(id)
    return render(request, 'pets/listar_pet.html', {'pet': pet, 'consultas': consultas})

def editar_pet(request, id):
    pet_antigo = pet_service.listar_pet_id(id)
    form_pet = pet_forms.PetForm(request.POST or None, instance=pet_antigo)
    if form_pet.is_valid():
        dono = form_pet.cleaned_data["dono"]
        nome = form_pet.cleaned_data["nome"]
        cor = form_pet.cleaned_data["cor"]
        nascimento = form_pet.cleaned_data["nascimento"]
        categoria = form_pet.cleaned_data["categoria"]
        pet_novo = pet.Pet(dono=dono, nome=nome, cor=cor, nascimento=nascimento,
                                    categoria=categoria)
        pet_service.editar_pet(pet_antigo, pet_novo)
        return redirect('listar_pets')
    return render(request, 'pets/form_pet.html', {'form_pet': form_pet})

app/templates/pets/form_pet.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Cadastro de Pet
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de pet</h3>
    </div>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form_pet.nome.errors }}
                <label>Nome: </label>
                {{ form_pet.nome|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_pet.nascimento.errors }}
                <label>Data de nascimento: </label>
                {{ form_pet.nascimento|addclass:'form-control' }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_pet.categoria.errors }}
                        <label>Categoria: </label>
                        {{ form_pet.categoria|addclass:'form-control' }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_pet.cor.errors }}
                        <label>Cor: </label>
                        {{ form_pet.cor|addclass:'form-control' }}
                    </div>
                </div>

            </div>

            <div class="form-group">
                <input type="submit" name="Cadastrar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/pets/listar_pet.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Listagem de Pet
{% endblock title %}

{% block content %}
<section class="content">

    <div class="row">
        <div class="col-md-3">
            <div class="card card-primary card-outline">
                <div class="card-body box-profile">
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle" src="{% static 'img' %}/pets.jpg"
                             alt="User profile picture">
                    </div>
                    <h2 class="profile-username text-center">{{pet.nome}}</h2>
                    <p class="text-muted text-center">{{pet.get_categoria_display}}</p>
                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Data nascimento:</b> <a class="float-right">{{pet.nascimento}}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Cor:</b> <a class="float-right">{{pet.get_cor_display}}</a>
                        </li>
                    </ul>

                    <div class="row">
                        <div class="col-md-12">
                            <a href="{% url 'cadastrar_consulta' pet.id %}" class="btn btn-primary btn-block">
                                Cadastrar consulta
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header p-2">
                    <ul class="nav nav-pills">
                        <li class="active">
                            <div class="time-label">
                                <strong><i class="far fa-file-alt mr-1"></i> Historico</strong>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">

                                    {% for consulta in consultas %}
                                    <div class="timeline">
                                        <div class="time-label">
                                            <span class="bg-red">{{consulta.data}}</span>
                                        </div>

                                        <div>
                                            <i class="fa fa-paw bg-blue"></i>
                                            <div class="timeline-item">
                                                <h3 class="timeline-header">
                                                    <b>Nome: </b>
                                                    {{consulta.pet.nome}}
                                                </h3>
                                            <div class="timeline-body">
                                                <b>Motivo da consulta: </b>
                                                {{consulta.motivo_consulta}}
                                            </div>
                                            <div class="timeline-footer">
                                                <a class="btn btn-primary btn-sm" href="{% url 'listar_consulta_id' consulta.id %}">
                                                    <i class="fa fa-print"></i>
                                                    Visualizar consulta
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div><!-- container-fluid -->
                    </div>
                </div>
            </div>
        </div>
</section>

{% endblock content %}